# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c010d140ded42ae088baa8f89bfd6d29ddea9936114364bd82bd423a19bfec1f712ce57febe97240dff9902ac162876f98c7b3e43e4c22c760f31795ed9f502c

test:
  secret_key_base: 92fc8d53b5f65681865845ba6ee45e46685639b65c2fbb5148350fe66b63b2dbc29f1b64f8af3eb70b886c698749a9537503faedb983fa804bcc1bc87a4c1afc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
